### ISSUE TITLE
How to get players' positions and actions in one round for every game unit time

### ISSUE THREAD

**Issue by hx-w** [ZaharX97/CSGOdemoPythonParser#1]
I want to make a replay function within a single round. How can I  use this demo parser to get the positions and actions of all players  during a specific round as the game time changes?

**Comment by ZaharX97** [comment]
About the player positions, i uploaded an example file that gets player positions every game tick > [check this](https://github.com/ZaharX97/CSGOdemoPythonParser/commit/30aa33a729710ef07aed4ce7c7d271a1d6c942a1)  
For other actions, you might want to look at the game events list and do a specific thing for a specific event. Like when a player throws a grenade, save that in a variable or whatever you need for your replay.  
  
As a sidenote, this parser is actually kind of slow compared to [https://github.com/markus-wa/demoinfocs-golang](url). It takes almost 60 seconds to do what the other does in 1 second :)

**Comment by hx-w** [comment]
> About the player positions, i uploaded an example file that gets player positions every game tick > [check this](https://github.com/ZaharX97/CSGOdemoPythonParser/commit/30aa33a729710ef07aed4ce7c7d271a1d6c942a1)
> For other actions, you might want to look at the game events list and do a specific thing for a specific event. Like when a player throws a grenade, save that in a variable or whatever you need for your replay.
> 
> As a sidenote, this parser is actually kind of slow compared to [https://github.com/markus-wa/demoinfocs-golang](url). It takes almost 60 seconds to do what the other does in 1 second :)

It's very helpful. Thanks for your sharing 👍XD

**Comment by hx-w** [comment]
I just ran the program, and I found that the function "print_player_positions"https://github.com/ZaharX97/CSGOdemoPythonParser/blob/5a669c58df7146afb7bf587b2b0a9b660e66281a/example/player_pos_funcs.py#L30 may never be called in parsering my demo... Does this works perfectly in your computer, or just my demo's problem.

**Comment by ZaharX97** [comment]
I updated the main program and forgot to also upload it, sry :)  
It should work if you download it again, or open your copy of DemoParser.py and add the lines 
[102, 106 - 108](https://github.com/ZaharX97/CSGOdemoPythonParser/commit/56b46c0049d552abe39b3084299bfd8c1eba3ebd#diff-1f248bdcfdb1fa56ee3ef5d23496ad38R102)  
Also, I made [this change](https://github.com/ZaharX97/CSGOdemoPythonParser/commit/1559d3b1f89f86df85a4d8d558f0b68839ce865f) because the player Z position was wrong. From my tests it looks the same as the one in cl_showplayerpos 1 in game

**Comment by hx-w** [comment]
> I updated the main program and forgot to also upload it, sry :)
> It should work if you download it again, or open your copy of DemoParser.py and add the lines
> [102, 106 - 108](https://github.com/ZaharX97/CSGOdemoPythonParser/commit/56b46c0049d552abe39b3084299bfd8c1eba3ebd#diff-1f248bdcfdb1fa56ee3ef5d23496ad38R102)
> Also, I made [this change](https://github.com/ZaharX97/CSGOdemoPythonParser/commit/1559d3b1f89f86df85a4d8d558f0b68839ce865f) because the player Z position was wrong. From my tests it looks the same as the one in cl_showplayerpos 1 in game

It works well. Thank you!
